const players = [
  
  // BATSMEN
  { name: "Virat Kohli", role: "Batsman", base: 2, rating: 96, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Rohit Sharma", role: "Batsman", base: 2, rating: 95, overseas: false, style: "RHB Opener", country: "INDIA" },
  { name: "Chris Gayle", role: "Batsman", base: 2, rating: 99, overseas: true, style: "LHB Opener (Legend)", country: "WEST INDIES" }, // Legend
  { name: "AB de Villiers", role: "Batsman", base: 2, rating: 99, overseas: true, style: "RHB 360 (Legend)", country: "SOUTH AFRICA" }, // Legend
  { name: "Suresh Raina", role: "Batsman", base: 2, rating: 94, overseas: false, style: "LHB Top Order (Legend)", country: "INDIA" }, // Legend
  { name: "Shubman Gill", role: "Batsman", base: 2, rating: 93, overseas: false, style: "RHB Opener", country: "INDIA" },
  { name: "Ruturaj Gaikwad", role: "Batsman", base: 2, rating: 89, overseas: false, style: "RHB Opener", country: "INDIA" },
  { name: "Yashasvi Jaiswal", role: "Batsman", base: 2, rating: 94, overseas: false, style: "LHB Opener", country: "INDIA" },
  { name: "Suryakumar Yadav", role: "Batsman", base: 2, rating: 97, overseas: false, style: "RHB Aggressor", country: "INDIA" },
  { name: "Sai Sudharsan", role: "Batsman", base: 1, rating: 94, overseas: false, style: "LHB Top Order", country: "INDIA" }, // 2026 form
  { name: "Vaibhav Suryavanshi", role: "Batsman", base: 2, rating: 99, overseas: false, style: "LHB Top Order", country: "INDIA" }, // 36-ball hundred
  { name: "Donavon Ferreira", role: "Batsman", base: 1, rating: 85, overseas: true, style: "RHB Finisher", country: "SOUTH AFRICA" },
  { name: "Shimron Hetmyer", role: "Batsman", base: 1, rating: 88, overseas: true, style: "LHB Finisher", country: "WEST INDIES" },
  { name: "Tilak Varma", role: "Batsman", base: 1, rating: 92, overseas: false, style: "LHB Middle Order", country: "INDIA" },
  { name: "Rajat Patidar", role: "Batsman", base: 1, rating: 90, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Rinku Singh", role: "Batsman", base: 1, rating: 91, overseas: false, style: "LHB Finisher", country: "INDIA" },
  { name: "Nitish Rana", role: "Batsman", base: 1, rating: 82, overseas: false, style: "LHB Middle Order", country: "INDIA" },
  { name: "Devdutt Padikkal", role: "Batsman", base: 1, rating: 78, overseas: false, style: "LHB Top Order", country: "INDIA" },
  { name: "Rahul Tripathi", role: "Batsman", base: 1, rating: 81, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Priyansh Arya", role: "Batsman", base: 2, rating: 91, overseas: false, style: "LHB Opener", country: "INDIA" },
  { name: "Karun Nair", role: "Batsman", base: 0.5, rating: 68, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Sarfaraz Khan", role: "Batsman", base: 0.5, rating: 84, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Manish Pandey", role: "Batsman", base: 0.5, rating: 72, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Shahrukh Khan", role: "Batsman", base: 0.5, rating: 83, overseas: false, style: "RHB Finisher", country: "INDIA" },
  { name: "Abdul Samad", role: "Batsman", base: 0.5, rating: 80, overseas: false, style: "RHB Finisher", country: "INDIA" },
  { name: "Dewald Brevis", role: "Batsman", base: 0.5, rating: 85, overseas: true, style: "RHB Aggressive", country: "SOUTH AFRICA" },
  { name: "Mayank Agarwal", role: "Batsman", base: 0.75, rating: 74, overseas: false, style: "RHB Opener", country: "INDIA" },
  { name: "C Andre Siddharth", role: "Batsman", base: 0.2, rating: 84, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Tristan Stubbs", role: "Batsman", base: 2, rating: 94, overseas: true, style: "RHB Middle Order", country: "SOUTH AFRICA" },
  { name: "Angkrish Raghuvanshi", role: "Batsman", base: 0.2, rating: 88, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Nehal Wadhera", role: "Batsman", base: 0.5, rating: 86, overseas: false, style: "LHB Middle Order", country: "INDIA" },
  { name: "Aniket Verma", role: "Batsman", base: 0.2, rating: 77, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Atharva Taide", role: "Batsman", base: 0.2, rating: 81, overseas: false, style: "LHB Opener", country: "INDIA" },
  { name: "Shaik Rasheed", role: "Batsman", base: 0.2, rating: 79, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Himmat Singh", role: "Batsman", base: 0.2, rating: 78, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Swastik Chikara", role: "Batsman", base: 0.2, rating: 81, overseas: false, style: "RHB Aggressive", country: "INDIA" },
  { name: "Travis Head", role: "Batsman", base: 2, rating: 96, overseas: true, style: "LHB Opener", country: "AUSTRALIA" },
  { name: "David Warner", role: "Batsman", base: 2, rating: 90, overseas: true, style: "LHB Opener", country: "AUSTRALIA" },
  { name: "Tim David", role: "Batsman", base: 2, rating: 87, overseas: true, style: "RHB Finisher", country: "AUSTRALIA" },
  { name: "Shubham Dubey", role: "Batsman", base: 0.2, rating: 81, overseas: false, style: "LHB Finisher", country: "INDIA" },
  { name: "Harnoor Singh", role: "Batsman", base: 0.2, rating: 78, overseas: false, style: "LHB Opener", country: "INDIA" },
  { name: "Mathew Breetzke", role: "Batsman", base: 0.5, rating: 83, overseas: true, style: "RHB Top Order", country: "SOUTH AFRICA" },
  { name: "Sachin Baby", role: "Batsman", base: 0.2, rating: 79, overseas: false, style: "LHB Middle Order", country: "INDIA" },
  { name: "Abhinav Manohar", role: "Batsman", base: 0.3, rating: 82, overseas: false, style: "RHB Finisher", country: "INDIA" },
  { name: "Bevon Jacobs", role: "Batsman", base: 0.2, rating: 76, overseas: true, style: "RHB Aggressive", country: "NEW ZEALAND" },
  { name: "Steve Smith", role: "Batsman", base: 2, rating: 88, overseas: true, style: "RHB Anchor", country: "AUSTRALIA" },
  { name: "Charith Asalanka", role: "Batsman", base: 1, rating: 85, overseas: true, style: "LHB Middle Order", country: "SRI LANKA" },
  { name: "Yash Dhull", role: "Batsman", base: 0.3, rating: 78, overseas: false, style: "RHB Top Order", country: "INDIA" },

  
  // WICKETKEEPERS
  { name: "MS Dhoni", role: "Wicketkeeper", base: 2, rating: 95, overseas: false, style: "RHB Finisher", country: "INDIA" },
  { name: "Heinrich Klaasen", role: "Wicketkeeper", base: 2, rating: 99, overseas: true, style: "RHB Elite Finisher", country: "SOUTH AFRICA" },
  { name: "Rishabh Pant", role: "Wicketkeeper", base: 2, rating: 93, overseas: false, style: "LHB Aggressive", country: "INDIA" },
  { name: "KL Rahul", role: "Wicketkeeper", base: 2, rating: 98, overseas: false, style: "RHB Opener", country: "INDIA" },
  { name: "Jos Buttler", role: "Wicketkeeper", base: 2, rating: 92, overseas: true, style: "RHB Opener", country: "ENGLAND" },
  { name: "Ishan Kishan", role: "Wicketkeeper", base: 1, rating: 95, overseas: false, style: "LHB Opener", country: "INDIA" },
  { name: "Sanju Samson", role: "Wicketkeeper", base: 1, rating: 97, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Nicholas Pooran", role: "Wicketkeeper", base: 1, rating: 96, overseas: true, style: "LHB Finisher", country: "WEST INDIES" },
  { name: "Phil Salt", role: "Wicketkeeper", base: 1, rating: 91, overseas: true, style: "RHB Opener", country: "ENGLAND" },
  { name: "Jitesh Sharma", role: "Wicketkeeper", base: 1, rating: 84, overseas: false, style: "RHB Finisher", country: "INDIA" },
  { name: "Dhruv Jurel", role: "Wicketkeeper", base: 2, rating: 89, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Quinton de Kock", role: "Wicketkeeper", base: 1, rating: 93, overseas: true, style: "LHB Opener", country: "SOUTH AFRICA" },
  { name: "Josh Inglis", role: "Wicketkeeper", base: 2, rating: 90, overseas: true, style: "RHB Aggressive", country: "AUSTRALIA" },
  { name: "Abishek Porel", role: "Wicketkeeper", base: 0.5, rating: 86, overseas: false, style: "LHB Top Order", country: "INDIA" },
  { name: "Anuj Rawat", role: "Wicketkeeper", base: 0.2, rating: 81, overseas: false, style: "LHB Middle Order", country: "INDIA" },
  { name: "Luvnith Sisodia", role: "Wicketkeeper", base: 0.2, rating: 78, overseas: false, style: "LHB Aggressive", country: "INDIA" },
  { name: "Aryan Juyal", role: "Wicketkeeper", base: 0.2, rating: 80, overseas: false, style: "RHB Top Order", country: "INDIA" },
  { name: "Prabhsimran Singh", role: "Wicketkeeper", base: 1, rating: 92, overseas: false, style: "RHB Opener", country: "INDIA" },
  { name: "Robin Minz", role: "Wicketkeeper", base: 0.2, rating: 82, overseas: false, style: "LHB Aggressive", country: "INDIA" },
  { name: "Krishnan Shrijith", role: "Wicketkeeper", base: 0.2, rating: 77, overseas: false, style: "LHB Aggressive", country: "INDIA" },
  { name: "Kunal Singh Rathore", role: "Wicketkeeper", base: 0.2, rating: 77, overseas: false, style: "LHB Middle Order", country: "INDIA" },
  { name: "Kumar Kushagra", role: "Wicketkeeper", base: 0.5, rating: 83, overseas: false, style: "RHB Middle Order", country: "INDIA" },
  { name: "Rahmanullah Gurbaz", role: "Wicketkeeper", base: 1.5, rating: 88, overseas: true, style: "RHB Opener", country: "AFGHANISTAN" },
  { name: "Jonny Bairstow", role: "Wicketkeeper", base: 1, rating: 87, overseas: true, style: "RHB Opener", country: "ENGLAND" },
  { name: "KS Bharat", role: "Wicketkeeper", base: 0.75, rating: 76, overseas: false, style: "RHB Top Order", country: "INDIA" },

  
  // ALL-ROUNDERS
  { name: "Shane Watson", role: "All-rounder", base: 2, rating: 96, overseas: true, style: "RH Fast-Medium (Legend)", country: "AUSTRALIA" },
  { name: "Hardik Pandya", role: "All-rounder", base: 2, rating: 92, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Ravindra Jadeja", role: "All-rounder", base: 2, rating: 96, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Glenn Maxwell", role: "All-rounder", base: 2, rating: 89, overseas: true, style: "RH Spin", country: "AUSTRALIA" },
  { name: "Ben Stokes", role: "All-rounder", base: 2, rating: 90, overseas: true, style: "RH Fast-Medium", country: "ENGLAND" },
  { name: "Mitchell Santner", role: "All-rounder", base: 2, rating: 91, overseas: true, style: "LH Spin", country: "NEW ZEALAND" },
  { name: "Jimmy Neesham", role: "All-rounder", base: 2, rating: 86, overseas: true, style: "RH Medium-Fast", country: "NEW ZEALAND" },
  { name: "Axar Patel", role: "All-rounder", base: 1, rating: 93, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Cameron Green", role: "All-rounder", base: 1, rating: 91, overseas: true, style: "RH Fast-Medium", country: "AUSTRALIA" },
  { name: "Marcus Stoinis", role: "All-rounder", base: 1, rating: 90, overseas: true, style: "RH Medium-Fast", country: "AUSTRALIA" },
  { name: "Mitchell Marsh", role: "All-rounder", base: 1, rating: 94, overseas: true, style: "RH Medium-Fast", country: "AUSTRALIA" },
  { name: "Wanindu Hasaranga", role: "All-rounder", base: 1, rating: 91, overseas: true, style: "RH Leg Spin", country: "SRI LANKA" },
  { name: "Rahul Tewatia", role: "All-rounder", base: 1, rating: 88, overseas: false, style: "RH Leg Spin", country: "INDIA" },
  { name: "Shivam Dube", role: "All-rounder", base: 2, rating: 93, overseas: false, style: "RH Medium", country: "INDIA" },
  { name: "Abhishek Sharma", role: "All-rounder", base: 2, rating: 98, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Sunil Narine", role: "All-rounder", base: 1.5, rating: 96, overseas: true, style: "RH Off Spin", country: "WEST INDIES" },
  { name: "Andre Russell", role: "All-rounder", base: 2, rating: 95, overseas: true, style: "RH Fast-Medium", country: "WEST INDIES" },
  { name: "Daryl Mitchell", role: "All-rounder", base: 2, rating: 89, overseas: true, style: "RH Medium", country: "NEW ZEALAND" },
  { name: "Ravichandran Ashwin", role: "All-rounder", base: 2, rating: 91, overseas: false, style: "RH Off Spin", country: "INDIA" },
  { name: "Rachin Ravindra", role: "All-rounder", base: 2, rating: 92, overseas: true, style: "LH Spin", country: "NEW ZEALAND" },
  { name: "Jamie Overton", role: "All-rounder", base: 1.5, rating: 87, overseas: true, style: "RH Fast", country: "ENGLAND" },
  { name: "Sai Kishore", role: "All-rounder", base: 0.5, rating: 89, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Venkatesh Iyer", role: "All-rounder", base: 2, rating: 88, overseas: false, style: "RH Medium", country: "INDIA" },
  { name: "Shardul Thakur", role: "All-rounder", base: 0.5, rating: 85, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Arshin Kulkarni", role: "All-rounder", base: 0.2, rating: 82, overseas: false, style: "RH Medium-Fast", country: "INDIA" },
  { name: "Raj Bawa", role: "All-rounder", base: 0.2, rating: 79, overseas: false, style: "RH Medium-Fast", country: "INDIA" },
  { name: "Liam Livingstone", role: "All-rounder", base: 2, rating: 89, overseas: true, style: "RH Spin", country: "ENGLAND" },
  { name: "Sam Curran", role: "All-rounder", base: 2, rating: 91, overseas: true, style: "LH Fast-Medium", country: "ENGLAND" },
  { name: "Krunal Pandya", role: "All-rounder", base: 0.5, rating: 88, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Washington Sundar", role: "All-rounder", base: 0.5, rating: 87, overseas: false, style: "RH Off Spin", country: "INDIA" },
  { name: "Vijay Shankar", role: "All-rounder", base: 0.5, rating: 80, overseas: false, style: "RH Medium-Fast", country: "INDIA" },
  { name: "Jayant Yadav", role: "All-rounder", base: 0.5, rating: 81, overseas: false, style: "RH Off Spin", country: "INDIA" },
  { name: "Aaron Hardie", role: "All-rounder", base: 1, rating: 87, overseas: true, style: "RH Medium-Fast", country: "AUSTRALIA" },
  { name: "Jacob Bethell", role: "All-rounder", base: 0.5, rating: 86, overseas: true, style: "LH Spin", country: "ENGLAND" },
  { name: "Kamindu Mendis", role: "All-rounder", base: 0.5, rating: 89, overseas: true, style: "Ambidextrous Spin", country: "SRI LANKA" },
  { name: "Harpreet Brar", role: "All-rounder", base: 0.5, rating: 88, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Karim Janat", role: "All-rounder", base: 0.5, rating: 84, overseas: true, style: "RH Medium-Fast", country: "AFGHANISTAN" },
  { name: "Mahipal Lomror", role: "All-rounder", base: 0.5, rating: 86, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Nitish Kumar Reddy", role: "All-rounder", base: 1.5, rating: 91, overseas: false, style: "RH Medium-Fast", country: "INDIA" },
  { name: "Anukul Roy", role: "All-rounder", base: 0.2, rating: 83, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Musheer Khan", role: "All-rounder", base: 0.2, rating: 85, overseas: false, style: "LH Spin", country: "INDIA" },
  { name: "Rajvardhan Hangargekar", role: "All-rounder", base: 0.4, rating: 82, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Dwaine Pretorius", role: "All-rounder", base: 1, rating: 84, overseas: true, style: "RH Medium-Fast", country: "SOUTH AFRICA" },

  
  // BOWLERS
  { name: "Lasith Malinga", role: "Bowler", base: 2, rating: 99, overseas: true, style: "RH Sling Fast (Legend)", country: "SRI LANKA" },
  { name: "Jasprit Bumrah", role: "Bowler", base: 2, rating: 92, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Mohammed Shami", role: "Bowler", base: 2, rating: 95, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Mohammed Siraj", role: "Bowler", base: 2, rating: 90, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Rashid Khan", role: "Bowler", base: 2, rating: 97, overseas: true, style: "RH Leg Spin", country: "AFGHANISTAN" },
  { name: "Pat Cummins", role: "Bowler", base: 2, rating: 96, overseas: true, style: "RH Fast", country: "AUSTRALIA" },
  { name: "Trent Boult", role: "Bowler", base: 2, rating: 94, overseas: true, style: "LH Fast", country: "NEW ZEALAND" },
  { name: "Jofra Archer", role: "Bowler", base: 2, rating: 92, overseas: true, style: "RH Fast", country: "ENGLAND" },
  { name: "Josh Hazlewood", role: "Bowler", base: 2, rating: 98, overseas: true, style: "RH Fast", country: "AUSTRALIA" },
  { name: "Mitchell Starc", role: "Bowler", base: 2, rating: 95, overseas: true, style: "LH Fast", country: "AUSTRALIA" },
  { name: "Ravi Bishnoi", role: "Bowler", base: 2, rating: 91, overseas: false, style: "RH Leg Spin", country: "INDIA" },
  { name: "Nandre Burger", role: "Bowler", base: 2, rating: 90, overseas: true, style: "LH Fast", country: "SOUTH AFRICA" },
  { name: "Kuldeep Yadav", role: "Bowler", base: 2, rating: 96, overseas: false, style: "LH Chinaman", country: "INDIA" },
  { name: "Yuzvendra Chahal", role: "Bowler", base: 2, rating: 94, overseas: false, style: "RH Leg Spin", country: "INDIA" },
  { name: "Arshdeep Singh", role: "Bowler", base: 2, rating: 85, overseas: false, style: "LH Fast-Medium", country: "INDIA" },
  { name: "Avesh Khan", role: "Bowler", base: 1, rating: 88, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Bhuvneshwar Kumar", role: "Bowler", base: 1, rating: 90, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Mayank Yadav", role: "Bowler", base: 0.5, rating: 96, overseas: false, style: "RH Express Fast", country: "INDIA" },
  { name: "Deepak Chahar", role: "Bowler", base: 0.5, rating: 87, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Prasidh Krishna", role: "Bowler", base: 0.5, rating: 85, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Ishant Sharma", role: "Bowler", base: 0.5, rating: 83, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "T Natarajan", role: "Bowler", base: 0.5, rating: 92, overseas: false, style: "LH Fast-Medium", country: "INDIA" },
  { name: "Gerald Coetzee", role: "Bowler", base: 2, rating: 91, overseas: true, style: "RH Fast", country: "SOUTH AFRICA" },
  { name: "Mujeeb Ur Rahman", role: "Bowler", base: 2, rating: 89, overseas: true, style: "RH Off Spin", country: "AFGHANISTAN" },
  { name: "Maheesh Theekshana", role: "Bowler", base: 2, rating: 90, overseas: true, style: "RH Mystery Spin", country: "SRI LANKA" },
  { name: "Alzarri Joseph", role: "Bowler", base: 2, rating: 88, overseas: true, style: "RH Fast", country: "WEST INDIES" },
  { name: "Naveen-ul-Haq", role: "Bowler", base: 2, rating: 91, overseas: true, style: "RH Fast-Medium", country: "AFGHANISTAN" },
  { name: "Umesh Yadav", role: "Bowler", base: 1.5, rating: 85, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Karn Sharma", role: "Bowler", base: 0.5, rating: 84, overseas: false, style: "RH Leg Spin", country: "INDIA" },
  { name: "Akash Madhwal", role: "Bowler", base: 0.3, rating: 86, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Mukesh Kumar", role: "Bowler", base: 1.5, rating: 90, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Mohit Sharma", role: "Bowler", base: 1, rating: 89, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Lockie Ferguson", role: "Bowler", base: 1.5, rating: 92, overseas: true, style: "RH Fast", country: "NEW ZEALAND" },
  { name: "Anrich Nortje", role: "Bowler", base: 2, rating: 92, overseas: true, style: "RH Fast", country: "SOUTH AFRICA" },
  { name: "Tushar Deshpande", role: "Bowler", base: 1, rating: 88, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
  { name: "Harshit Rana", role: "Bowler", base: 1.5, rating: 93, overseas: false, style: "RH Fast", country: "INDIA" },
  { name: "Khaleel Ahmed", role: "Bowler", base: 1.5, rating: 91, overseas: false, style: "LH Fast-Medium", country: "INDIA" },
  { name: "Vijaykumar Vyshak", role: "Bowler", base: 0.5, rating: 87, overseas: false, style: "RH Fast-Medium", country: "INDIA" },
];

export default players;