const players = [

  { name: "Virat Kohli", role: "Batsman", base: 2, rating: 95, overseas: false },
  { name: "Rohit Sharma", role: "Batsman", base: 2, rating: 93, overseas: false },
  { name: "Shubman Gill", role: "Batsman", base: 2, rating: 92, overseas: false },
  { name: "Ruturaj Gaikwad", role: "Batsman", base: 2, rating: 88, overseas: false },
  { name: "Yashasvi Jaiswal", role: "Batsman", base: 2, rating: 91, overseas: false },
  { name: "MS Dhoni", role: "Wicketkeeper", base: 2, rating: 90, overseas: false },
  { name: "Rishabh Pant", role: "Wicketkeeper", base: 2, rating: 92, overseas: false },
  { name: "KL Rahul", role: "Wicketkeeper", base: 2, rating: 90, overseas: false },
  { name: "Jos Buttler", role: "Wicketkeeper", base: 2, rating: 93, overseas: true },
  { name: "Hardik Pandya", role: "All-rounder", base: 2, rating: 91, overseas: false },
  { name: "Ravindra Jadeja", role: "All-rounder", base: 2, rating: 92, overseas: false },
  { name: "Glenn Maxwell", role: "All-rounder", base: 2, rating: 90, overseas: true },
  { name: "Ben Stokes", role: "All-rounder", base: 2, rating: 91, overseas: true },
  { name: "Jasprit Bumrah", role: "Bowler", base: 2, rating: 96, overseas: false },
  { name: "Mohammed Shami", role: "Bowler", base: 2, rating: 91, overseas: false },
  { name: "Mohammed Siraj", role: "Bowler", base: 2, rating: 89, overseas: false },
  { name: "Rashid Khan", role: "Bowler", base: 2, rating: 95, overseas: true },
  { name: "Pat Cummins", role: "Bowler", base: 2, rating: 92, overseas: true },
  { name: "Trent Boult", role: "Bowler", base: 2, rating: 91, overseas: true },

  { name: "Sai Sudharsan", role: "Batsman", base: 1, rating: 82, overseas: false },
  { name: "Tilak Varma", role: "Batsman", base: 1, rating: 84, overseas: false },
  { name: "Rajat Patidar", role: "Batsman", base: 1, rating: 80, overseas: false },
  { name: "Rinku Singh", role: "Batsman", base: 1, rating: 85, overseas: false },
  { name: "Nitish Rana", role: "Batsman", base: 1, rating: 78, overseas: false },
  { name: "Devdutt Padikkal", role: "Batsman", base: 1, rating: 79, overseas: false },
  { name: "Rahul Tripathi", role: "Batsman", base: 1, rating: 80, overseas: false },
  { name: "Ishan Kishan", role: "Wicketkeeper", base: 1, rating: 83, overseas: false },
  { name: "Sanju Samson", role: "Wicketkeeper", base: 1, rating: 85, overseas: false },
  { name: "Nicholas Pooran", role: "Wicketkeeper", base: 1, rating: 88, overseas: true },
  { name: "Phil Salt", role: "Wicketkeeper", base: 1, rating: 82, overseas: true },
  { name: "Jitesh Sharma", role: "Wicketkeeper", base: 1, rating: 78, overseas: false },
  { name: "Axar Patel", role: "All-rounder", base: 1, rating: 85, overseas: false },
  { name: "Cameron Green", role: "All-rounder", base: 1, rating: 86, overseas: true },
  { name: "Marcus Stoinis", role: "All-rounder", base: 1, rating: 84, overseas: true },
  { name: "Mitchell Marsh", role: "All-rounder", base: 1, rating: 86, overseas: true },
  { name: "Wanindu Hasaranga", role: "All-rounder", base: 1, rating: 87, overseas: true },
  { name: "Rahul Tewatia", role: "All-rounder", base: 1, rating: 80, overseas: false },
  { name: "Shivam Dube", role: "All-rounder", base: 1, rating: 82, overseas: false },
  { name: "Kuldeep Yadav", role: "Bowler", base: 1, rating: 85, overseas: false },
  { name: "Yuzvendra Chahal", role: "Bowler", base: 1, rating: 86, overseas: false },
  { name: "Arshdeep Singh", role: "Bowler", base: 1, rating: 84, overseas: false },
  { name: "Avesh Khan", role: "Bowler", base: 1, rating: 80, overseas: false },
  { name: "Bhuvneshwar Kumar", role: "Bowler", base: 1, rating: 83, overseas: false },

  { name: "Karun Nair", role: "Batsman", base: 0.5, rating: 65, overseas: false },
  { name: "Sarfaraz Khan", role: "Batsman", base: 0.5, rating: 72, overseas: false },
  { name: "Manish Pandey", role: "Batsman", base: 0.5, rating: 70, overseas: false },
  { name: "Shahrukh Khan", role: "Batsman", base: 0.5, rating: 68, overseas: false },
  { name: "Abdul Samad", role: "Batsman", base: 0.5, rating: 66, overseas: false },
  { name: "Himmat Singh", role: "Batsman", base: 0.5, rating: 62, overseas: false },
  { name: "Dhruv Jurel", role: "Wicketkeeper", base: 0.5, rating: 75, overseas: false },
  { name: "Quinton de Kock", role: "Wicketkeeper", base: 0.5, rating: 88, overseas: true },
  { name: "Romario Shepherd", role: "All-rounder", base: 0.5, rating: 75, overseas: true },
  { name: "Shardul Thakur", role: "All-rounder", base: 0.5, rating: 78, overseas: false },
  { name: "Abhishek Sharma", role: "All-rounder", base: 0.5, rating: 82, overseas: false },
  { name: "Washington Sundar", role: "All-rounder", base: 0.5, rating: 80, overseas: false },
  { name: "Krunal Pandya", role: "All-rounder", base: 0.5, rating: 79, overseas: false },
  { name: "Sunil Narine", role: "All-rounder", base: 0.5, rating: 88, overseas: true },
  { name: "Deepak Chahar", role: "Bowler", base: 0.5, rating: 80, overseas: false },
  { name: "Prasidh Krishna", role: "Bowler", base: 0.5, rating: 78, overseas: false },
  { name: "Ishant Sharma", role: "Bowler", base: 0.5, rating: 72, overseas: false },
  { name: "T Natarajan", role: "Bowler", base: 0.5, rating: 82, overseas: false },
  { name: "Arjun Tendulkar", role: "Bowler", base: 0.5, rating: 65, overseas: false },
  { name: "Mayank Yadav", role: "Bowler", base: 0.5, rating: 83, overseas: false },

  { name: "Devon Conway", role: "Batsman", base: 2, rating: 90, overseas: true },
  { name: "Steve Smith", role: "Batsman", base: 2, rating: 91, overseas: true },
  { name: "Daryl Mitchell", role: "All-rounder", base: 2, rating: 89, overseas: true },
  { name: "Gerald Coetzee", role: "Bowler", base: 2, rating: 88, overseas: true },
  { name: "Mujeeb Ur Rahman", role: "Bowler", base: 2, rating: 87, overseas: true },
  { name: "Maheesh Theekshana", role: "Bowler", base: 2, rating: 86, overseas: true },
  { name: "Alzarri Joseph", role: "Bowler", base: 2, rating: 88, overseas: true },
  { name: "Naveen Ul Haq", role: "Bowler", base: 2, rating: 85, overseas: true },
  { name: "Rahmanullah Gurbaz", role: "Wicketkeeper", base: 1.5, rating: 82, overseas: true },
  { name: "Umesh Yadav", role: "Bowler", base: 1.5, rating: 78, overseas: false },
  { name: "Jonny Bairstow", role: "Wicketkeeper", base: 1, rating: 86, overseas: true },
  { name: "Charith Asalanka", role: "Batsman", base: 1, rating: 80, overseas: true },
  { name: "Dwaine Pretorius", role: "All-rounder", base: 1, rating: 78, overseas: true },
  { name: "Deepak Hooda", role: "All-rounder", base: 0.75, rating: 75, overseas: false },
  { name: "KS Bharat", role: "Wicketkeeper", base: 0.75, rating: 72, overseas: false },
  { name: "Mayank Agarwal", role: "Batsman", base: 0.75, rating: 74, overseas: false },
  { name: "Mahipal Lomror", role: "All-rounder", base: 0.5, rating: 70, overseas: false },
  { name: "Karn Sharma", role: "Bowler", base: 0.5, rating: 68, overseas: false },
  { name: "Rajvardhan Hangargekar", role: "All-rounder", base: 0.4, rating: 65, overseas: false },
  { name: "Akash Madhwal", role: "Bowler", base: 0.3, rating: 68, overseas: false },
  { name: "Yash Dhull", role: "Batsman", base: 0.3, rating: 67, overseas: false },
  { name: "Abhinav Manohar", role: "Batsman", base: 0.3, rating: 66, overseas: false },

];

export default players;